name: servidor
description: DartGameServer é um servidor multiplayer totalmente escrita em dart usando TCP para conexão entre o cliente e o servidor.
version: 1.0.1
epository: https://github.com/matheusoreis/DartGameServer

environment:
  sdk: ^3.2.3

dependencies:
  ansicolor: ^2.0.2
  pocketbase: ^0.18.1
  http: ^1.2.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.2
